import Head from "next/head";
import { useState } from "react";
import { Done } from "../components/Done";
import { Incompleted } from "../components/InCompleted";
import { Input } from "../components/Input";
import { useOnClick } from "../hooks/useOnClick";

export default function Home() {
  const {
    todoText,
    inCompletedTodos,
    inDoneTodos,
    onChangeTodoText,
    onClickAdd,
    onClickDelete,
    onClickDone,
    onClickDoneDelete,
    onClickReturn,
  } = useOnClick();

  return (
    <div>
      <Head>
        <title>TO DO LIST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main class="container mx-auto max-w-4xl p-8">
        <h1 class="text-center text-3xl md:text-4xl">To Do List</h1>

        <Input
          todoText={todoText}
          onChangeTodoText={onChangeTodoText}
          onClickAdd={onClickAdd}
        />

        <Incompleted
          inCompletedTodos={inCompletedTodos}
          onClickDone={onClickDone}
          onClickDelete={onClickDelete}
        />

        <Done
          inDoneTodos={inDoneTodos}
          onClickReturn={onClickReturn}
          onClickDoneDelete={onClickDoneDelete}
        />
      </main>
    </div>
  );
}
