import Head from 'next/head'
import { useState } from 'react'
import { Done } from '../components/Done';
import { Incompleted } from '../components/InCompleted';
import { Input } from '../components/Input';

export default function Home() {

  const [todoText, setTodoText] = useState("");

  const [inCompletedTodos, setInCompletedTodos] = useState([]);

  const [inDoneTodos, setInDoneTodos] =useState([]);

  const onClickAdd = () => {
      if( todoText === "")return;
      const newTodos = [...inCompletedTodos,todoText];
      setInCompletedTodos(newTodos);
      setTodoText("");
  }


  const onChangeTodoText = (event) => setTodoText(event.target.value);

  const onClickDelete = (index) =>{
      const newTodos = [...inCompletedTodos];
      newTodos.splice(index,1);
      setInCompletedTodos(newTodos);
  }

  const onClickDone = (index) =>{
      const newTodos = [...inCompletedTodos];
      newTodos.splice(index,1);
      const newDone = [...inDoneTodos,inCompletedTodos[index]];

      setInCompletedTodos(newTodos);
      setInDoneTodos(newDone);
  }

  const onClickDoneDelete = (index) =>{
    const newDoneTodos = [...inDoneTodos];
    newDoneTodos.splice(index,1);
    setInDoneTodos(newDoneTodos);
}

  const  onClickReturn = (index) =>{
    const newDoneTodos = [...inDoneTodos];
    newDoneTodos.splice(index,1);

    const newTodos = [...inCompletedTodos,inDoneTodos[index]]


    setInCompletedTodos(newTodos);
    setInDoneTodos(newDoneTodos);
  }

  return (
    <div>
      <Head>
        <title>TO DO LIST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main class="container mx-auto max-w-4xl p-8">

        <h1 class="text-center text-3xl md:text-4xl">To Do List</h1>

      <Input todoText={todoText} onChangeTodoText={onChangeTodoText} onClickAdd={onClickAdd}/>

      <Incompleted inCompletedTodos={inCompletedTodos} onClickDone={onClickDone} onClickDelete={onClickDelete}/>

      <Done inDoneTodos={inDoneTodos} onClickReturn={onClickReturn} onClickDoneDelete={onClickDoneDelete}/>

      </main>

    </div>
  )
}
